### ISSUE TITLE
Can use to communicate iBoot iOS devices ?

### ISSUE THREAD

**Issue by planktonwhc** [IntergatedCircuits/LibUsbDfu#5]
hi, please manage docs how to communicate with iboot ios. like send file, send command, etc

**Comment by benedekkupper** [comment]
Wouldn't that be nice? The problem is, I have no idea about iBoot, and this library was written to support USB FW update through the standard DFU class (and its STMicroelectronics extension). So please first verify that the iBoot uses this DFU protocol (as opposed to a vendor specific one). Anyone picking up this task would need to reverse engineer the USB communication as a whole, so please attach USB bus capture of the whole update procedure, and the image file that was used.
